spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fake-apiDB
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        package-to-scan: com.microservice.fakeapi.infraestructure.entities
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    loadbalancer:
      ribbon:
        enable: true

topico:
  fake-api:
    consumer:
      nome: fake-api-consumer-products-v10
      group-id: javanauta
    producer:
      nome: fake-api-producer-products-v10

server:
  port: 8181
